site_name: Documentación
site_url: https://sitename.example
nav:
  - Inicio: index.md
  - Git y Markdown:
    - Instalación de MKdocs: pages/instalacionMKdocs.md
  - AWS - EC2 Despliegue Clásico:
    - VPC:
      - Creación de VPC y subredes: pages/instalacionVPC.md
    - EC2:
      - Creación de EC2: pages/instalacionEC2.md
      - Instalación de Nginx: pages/Nginx.md
      - Nginx en funcionamiento: pages/NginxFuncionamiento.md
  - Contenedores Docker:
    - Dockerización de MKdocs: pages/Dockerizacion.md
  - AWS - ECS:
    - Creación de ECS: pages/creacionECS.md
  - AWS - ECS con RDS y EFS:
    - Creación de RDS: pages/creacionRDS.md
    - Conexión con RDS: pages/conexionecsrds.md
    - Desplegar Wordpress: pages/desplegarWP.md
  - AWS y Github - Sitio Web Estático:
      - Página estática en S3: pages/paginaestaticas3.md
      - Cloudfront y ACM: pages/Cloudfront.md
      - WAF:
        - Crear una ACL: pages/waf.md
      - GitHub Actions: pages/GitHubActions.md
  - Terraform:
    - Práctica 1: pages/TerraEC2.md
    - Práctica 2: pages/TerraECS.md
    - Práctica 3: pages/TerraPrac3.md
    - Práctica 4: pages/TerraPrac4.md
    - Práctica 5: pages/TerraPrac5.md
  - Kubernetes:
    - Nginx básico: pages/Kub1.md
    - Skaffold: pages/Kub2.md
    - Kustomization: pages/Kub3.md
    - Helm:
      - Básico: pages/Helm1.md

theme:
  name: material
  logo: Recursos/Others/Basetis_Logotipo.svg
  favicon: Recursos/Others/favicon.ico
  language: es
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
    annotation: material/plus-circle
  features:
    - header.autohide
    - content.code.copy
  palette: 
# Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Modo día
      primary: custom
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Modo noche
      primary: deep purple
      accent: deep purple
  
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - admonition
  
plugins:
   - glightbox


extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/%C3%A1lvarogarc%C3%ADaoca%C3%B1a/

extra_css:
  - stylesheets/extra.css